release-amd64:
  image: $CI_REGISTRY/ion/ion-kit/builder
  script:
    - cmake -D CMAKE_BUILD_TYPE=Release -D ION_BUILD_TEST=off -D ION_BUILD_EXAMPLE=off -D ION_BUILD_ALL_BB=off -D ION_BUILD_DOC=off -D WITH_CUDA=off -D ION_BUNDLE_HALIDE=on .
    - make -j4 package
    - ls
  artifacts:
    paths:
      - ion-kit*
  tags:
    - amd64
    - docker
