macro(ion_import_building_block)
    cmake_policy(SET CMP0057 NEW)

    set(ION_BBS)
    set(ION_BB_INCLUDE_DIRS)
    set(ION_BB_LINK_DIRS)
    set(ION_BB_RUNTIME_ENVS)
    set(ION_BB_LIBRARIES)

    foreach(child ${ION_BB_DIR})
        set(config_file ${child}/config.cmake)
        if(EXISTS ${config_file} AND IS_DIRECTORY ${config_file})
            get_filename_component(BB_NAME ${child} NAME)
            set(BB_SRCS)
            set(RT_SRCS)
            set(INCLUDE_DIRS)
            set(LINK_DIRS)
            set(LIBRARIES)
            include(${config_file})
            list(APPEND ION_BBS ${BB_NAME})
            list(APPEND ION_BB_BB_SRCS ${BB_SRCS})
            list(APPEND ION_BB_RT_SRCS ${RT_SRCS})
            list(APPEND ION_BB_INCLUDE_DIRS ${INCLUDE_DIRS})
            if(IS_DIRECTORY ${ION_BB_DIR}/include)
                list(APPEND ION_BB_INCLUDE_DIRS ${ION_BB_DIR}/include)
            endif()
            list(APPEND ION_BB_LINK_DIRS    ${LINK_DIRS})
            list(APPEND ION_BB_LIBRARIES    ${LIBRARIES})
        endif()
    endforeach()

    message(STATUS "Found BBs: ${ION_BBS}")
    message(STATUS "  BB sources: ${ION_BB_BB_SRCS}")
    message(STATUS "  Runtime sources: ${ION_BB_RT_SRCS}")
    message(STATUS "  Include directories: ${ION_BB_INCLUDE_DIRS}")
    message(STATUS "  Link directories: ${ION_BB_LINK_DIRS}")
    message(STATUS "  Dependent Libaries: ${ION_BB_LIBRARIES}")
endmacro()
